package BIPublisher;

import javax.xml.ws.WebFault;

@WebFault(faultBean="com.oracle.xmlns.oxp.service.publicreportservice.InvalidParametersException",
  targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
  name="fault1")
public class InvalidParametersException
  extends Exception
{
  private com.oracle.xmlns.oxp.service.publicreportservice.InvalidParametersException faultInfo;

  public InvalidParametersException(String message,
                                    com.oracle.xmlns.oxp.service.publicreportservice.InvalidParametersException faultInfo)
  {
    super(message);
    this.faultInfo = faultInfo;
  }

  public InvalidParametersException(String message,
                                    com.oracle.xmlns.oxp.service.publicreportservice.InvalidParametersException faultInfo,
                                    Throwable t)
  {
    super(message,t);
    this.faultInfo = faultInfo;
  }

  public com.oracle.xmlns.oxp.service.publicreportservice.InvalidParametersException getFaultInfo()
  {
    return faultInfo;
  }

  public void setFaultInfo(com.oracle.xmlns.oxp.service.publicreportservice.InvalidParametersException faultInfo)
  {
    this.faultInfo = faultInfo;
  }
}
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)
