package BIPublisher;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

@WebServiceClient(wsdlLocation="http://localhost:7001/xmlpserver/services/PublicReportService?wsdl",
  targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
  name="PublicReportServiceService")
public class PublicReportServiceService
  extends Service
{
  private static URL wsdlLocationURL;

  private static Logger logger;
  static
  {
    try
    {
      logger = Logger.getLogger("BIPublisher.PublicReportServiceService");
      URL baseUrl = PublicReportServiceService.class.getResource(".");
      if (baseUrl == null)
      {
        wsdlLocationURL =
            PublicReportServiceService.class.getResource("http://localhost:7001/xmlpserver/services/PublicReportService?wsdl");
        if (wsdlLocationURL == null)
        {
          baseUrl = new File(".").toURL();
          wsdlLocationURL =
              new URL(baseUrl, "http://localhost:7001/xmlpserver/services/PublicReportService?wsdl");
        }
      }
      else
      {
                if (!baseUrl.getPath().endsWith("/")) {
         baseUrl = new URL(baseUrl, baseUrl.getPath() + "/");
}
                wsdlLocationURL =
            new URL(baseUrl, "http://localhost:7001/xmlpserver/services/PublicReportService?wsdl");
      }
    }
    catch (MalformedURLException e)
    {
      logger.log(Level.ALL,
          "Failed to create wsdlLocationURL using http://localhost:7001/xmlpserver/services/PublicReportService?wsdl",
          e);
    }
  }

  public PublicReportServiceService()
  {
    super(wsdlLocationURL,
          new QName("http://xmlns.oracle.com/oxp/service/PublicReportService",
                    "PublicReportServiceService"));
  }

  public PublicReportServiceService(URL wsdlLocation, QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  @WebEndpoint(name="PublicReportService")
  public BIPublisher.PublicReportService getPublicReportService()
  {
    return (BIPublisher.PublicReportService) super.getPort(new QName("http://xmlns.oracle.com/oxp/service/PublicReportService",
                                                                     "PublicReportService"),
                                                           BIPublisher.PublicReportService.class);
  }

  @WebEndpoint(name="PublicReportService")
  public BIPublisher.PublicReportService getPublicReportService(WebServiceFeature... features)
  {
    return (BIPublisher.PublicReportService) super.getPort(new QName("http://xmlns.oracle.com/oxp/service/PublicReportService",
                                                                     "PublicReportService"),
                                                           BIPublisher.PublicReportService.class,
                                                           features);
  }
}
